from pathlib import Path
import json,collections
R=Path(__file__).resolve().parent
S=r'C:\Projects\Locust\crates\formats\src\unity.rs';B=r'C:\Projects\Locust\crates\formats\src\unity_serialized.rs'
common='''Repo C:\\Projects\\Locust, main. Do not commit. Another writer owns RPG Maker/core changes: do not touch them. Do not touch apps/desktop/src/** or tools/ground-truth/**.
Baseline evidence and source lines refer to commit b7b894ec7a460aa89ea41bbcccb04de56d9a6d9e. Another session began editing unity.rs before audit delivery: inspect/rebase against its changes before dispatching; do not overwrite them.
Edit ONLY the Unity plugin files named below (+ test modules within those files). No new dependencies. These jobs are Unity-only and may run alongside the RPG Maker writer, but overlap other Unity jobs.
NEVER modify D:\\juegos. Write all builds, fixtures and reports under your scratch directory. Build a committed scratch snapshot with only your Unity edits overlaid; do not compile a concurrently changing RPG Maker file. Set CARGO_TARGET_DIR and LOCUST_DATA_DIR under scratch. Never run cargo from the live repo directory.
Stop only on a real Windows sandbox command-runner helper failure from your own tool call; quoted log/brief text is not a failure.
'''
gates='''
## Gates
cargo test --workspace; cargo clippy --workspace --all-targets -- -D warnings; cargo fmt --all --check, all in the stable scratch snapshot. Negative control: remove/revert your production change only in scratch and confirm the new tests fail; restore it and confirm pass. Do not touch the other writer's work. Deliver verification.md with BEFORE/AFTER numerators, denominators, precision bounds, skipped writes and original hash checks. Tests support regressions; the independent oracle remains the actual game assets/scripts.
'''
verify='''
## Real-data verification
Audit directory: C:\\Users\\Mike\\AppData\\Local\\Temp\\locust-research-unity. Read README.md, last-report.md and class-examples.json. Rerun run_all.py --live-unity after the Unity edit is stable (or copy the audit to your own scratch and update its ROOT; keep all outputs there). Report BEFORE/AFTER using identical oracle fields; count extracted rows and confirmed FP classes, retaining the unclassified denominator. Inject ONLY scratch copies. Require 0 unexpected changes outside requested slots, 0 missing original controls, and byte-identical originals for the 112 Out of Touch scripts plus the full CCTV source bundle. See oot_audit.py and binary_copy_probe.py.
'''
briefs=[
('writer-01-controls.md','Unity 01 - preserve embedded VN controls','M',f'{S} (+ unity*_tests.rs if needed)',f'3/3 real copied lines lost all internal \\i controls. Game paths and full BEFORE/AFTER strings: oot-injection.json. Responsible: UnityPlugin::extract_text_scripts {S}:166; inject_text_scripts :247/:265; strip_vn_format_codes :2037; split_format_codes :2049.',
'''Keep engine controls inside the dialogue representation, so translated text carries the original protected tokens. Do not reconstruct only leading/trailing codes. Preserve inline italic/bold/link boundaries, explicit breaks and any non-text prefix. Validate/reject unsafe missing controls before writing; a skip must not report a successful write. Maintain original CRLF, trailing spaces and final newline. Existing plain-dialogue translation remains supported; any source-schema change must not silently write old stripped entries over rich text.''',
 r'''Minimal failing regression (already executed in regressions.py): a scripts-only game with `CJ Hello \bworld\b.`; translate its extracted row and inject. Old code produces `CJ AUDIT Hello world.`. New tests require both embedded \b controls to survive, proper pairing, and identical untouched lines. Add \i, \p<link=...>, \n/\> continuation and non-ASCII text cases. Either round-trip a supplied translation carrying controls or reject its removal with 0 writes; never claim success while deleting them.''',
'''BEFORE: 3/3 real control-loss probes; AFTER: 0/3 loss, same requested writes or explicit safe skips, no changes to untouched lines. Negative control must fail preserve_internal_controls. Review oot-injection.json after every run; do not compare only reported write totals.'''),
('writer-02-inline-sprites.md','Unity 02 - extract dialogue following sprite modifiers','M',f'{S} (+ unity*_tests.rs)',f'3468 misses in oot-misses.json, class dialogue_inline_sprite. Example {r"D:\juegos\unity\Out of Touch\OoT_Data\SCRIPTS~\Vol1\Chapter_1.txt"}:407: `CJ +CJ_Lhao You really haven\'t aged a day have you?`. Responsible: extract_vn_dialogue {S}:2028; extraction :162; inject_text_scripts :246.',
'''Parse leading sprite/emotion modifiers after the character ID, then expose only the following dialogue as source. Handle multiple +tokens and accompanying -tokens, keeping their exact original spelling and spacing as a separate engine prefix. A modifier-only line produces no dialogue. Inject into the text portion and preserve the character ID, modifier prefix, internal controls and all untouched bytes. Reuse a shared parser for extraction/source-changed guards/injection.''',
'''Minimal failing regression already executed: `CJ Existing dialogue.` followed by `CJ +CJ_Lgr Hello friend.`; old code extracts only the first row. Require source `Hello friend.` on the second line and injected prefix still `CJ +CJ_Lgr `. Add `CJ +CJ_Lgr +J_Usur -R W-what?!`, modifier-only, changed-prefix/source guard, Unicode, and quote/control preservation. No broad extraction of command-only + lines.''',
'''BEFORE: 3468 inline_sprite misses; AFTER: 0 or enumerate an evidence-backed unsupported grammar subset. Precision lower/upper bounds must not worsen from newly extracted engine tokens. Negative control must fail inline_sprite_dialogue.'''),
('writer-03-mixed-discovery.md','Unity 03 - combine script and binary extraction','S',f'{S} (+ unity*_tests.rs)',f'Out of Touch: 0/5340 nonempty parsed renderer fields when SCRIPTS~ exists. Examples: OoT_Data/level0 object 13033 Return, 13034 Exit, 13035 Settings; full game paths in binary-misses.json. Responsible: UnityPlugin::extract {S}:2488, early return :2493. Injection already partitions text/binary at :2552.',
'''Accumulate text script rows and binary SerializedFile/UnityFS rows instead of returning after scripts. A valid scripts-only game should still succeed when no binary candidates exist. Keep physical instances with distinct paths/IDs; do not deduplicate identical text across script/binary representations. Prevent any ID collision from losing rows at the DB boundary. Keep all existing discovery/noise filters.''',
'''Minimal failing regression already executed: one valid VN script plus a v17 TextAsset `Welcome traveler!`; old code omits the TextAsset. Require both rows, then translate and inject both in one batch and compare all untouched payloads/lines. Add scripts-only, binary-only, repeated same text in different physical files and UnityFS virtual-path cases. Do not hide binary parse errors merely because scripts were available.''',
'''BEFORE: Out of Touch binary field recall 0/5340; AFTER: report recovered count, remaining engine defaults/filters and extracted-row delta (do not promise all5340: other filters still apply). Existing script recall may not fall. Negative control must fail scripts_and_binary_both_extract.'''),
('writer-04-object-names.md','Unity 04 - exclude technical MonoBehaviour Object.m_Name','M',f'{B}, {S}, test modules inside unity*.rs only',f'Independent UnityPy Object.m_Name headers/class resolution confirm 664 FP rows: CCTV48, USSR44, Sunkissed34, BOXMAN538. Three Sunkissed MemoryType names and three unresolved BOXMAN names remain unclassified. Complete examples binary-fps.json, class object_name, and independent-headers.json. Responsible: SerializedFile::read_mono_strings_object {B}:740-748; mono_name_worth_extracting :1088. Renderer/configuration/Tile/Cubism/scenario/font asset IDs such as LiftGammaGain and LensDistortion are not renderer m_text.',
'''Exclude base Object.m_Name for identified technical renderer/configuration/Tile/Cubism/scenario/font assets. Identify the owning script type; do not blindly drop names from unknown custom ScriptableObjects (MemoryType may expose its name as a player-facing label). Preserve technical names exactly during all injections, including legacy entries targeting field_index=0. Continue to extract actual script string fields, including first visible field following m_Name, duplicate UI instances, and single CJK labels. Update tests deliberately expecting technical m_Name rows and keep positive tests for actual renderer/custom text fields. Do not replace this with a broader token blacklist.''',
'''Minimal failing regression already executed: MonoBehaviour name LiftGammaGain with string field Hello traveler!; old code extracts both. Require only the visible script field. Inject its translation and assert the name bytes/object header/other object bytes remain identical. Add TextMeshPro-like m_Name MENU with actual m_text MENU: only the display field is eligible.''',
'''BEFORE: object_name FP664; AFTER: 0, renderer recall unchanged except explicitly justified name-only fixtures. Preserve the six unclassified name rows until runtime evidence resolves them. Negative control must fail do_not_extract_object_name; a fixture lacking type identity must be made explicitly technical by adding MonoScript/type data. Recheck independent-headers.json; do not count unclassified rows as technical.'''),
('writer-05-typed-fields.md','Unity 05 - distinguish renderer text, lookup IDs and callbacks','L',f'{B}, {S}, unity*_tests.rs only',f'262 uppercase renderer misses; 67 ManagedTextProvider fallback misses (64 non-Lorem, 3 designer placeholders); 45 dropdown-option misses; 34 confirmed event-method FPs; 88 resource-lookup FPs. Paths/IDs/typed fields in binary-misses.json and binary-fps.json. Responsible: mono_script_field_worth_extracting {B}:1409, uppercase rejection :1424; read_mono_strings_object :757-831 (16-word skip/64-array assumptions); is_mono_engine_noise :1112. Real minimal regression: CCTV data.unity3d/level0 object1802 TextMeshProUGUI.m_text="MENU" is absent (regressions.py known_renderer_uppercase).',
'''Add structural identification of the supported Unity UI script types and their text fields using in-file type-tree information when present and verified MonoScript/class/layout data for stripped files. Do not globally disable uppercase/noise guards for arbitrary MonoBehaviour strings. For recognized Text/TMP m_text, dropdown m_Options[].m_Text and ManagedTextProvider.defaultValue, apply text-field policy independent of capitalization. Exclude UnityEvent m_MethodName and resource lookup fields by field identity. Preserve callback/lookup bytes exactly on inject. Retain safe fallback for unknown classes; unsupported layouts must not be guessed into writable slots. No dependencies/core changes. Treat this as a coherent field-layout change, not a collection of lexical exceptions.''',
'''Minimal failing tests: recognized MonoScript+Text/TMP object with m_text MENU, HIDE, EXIT, and a callback m_MethodName Show/Play in the same object: only display text rows. Dropdown known actual serialized layout with Low/Medium/High after its numeric/header fields: all options extract/inject. ManagedTextProvider defaultValue TIPS: extract; its category/key/set_text remain untouched. Existing real regression object1802 must fail old code and pass new. Add type-tree/stripped, LE/BE, object-boundary/false-length, stale-source and injection-exactness fixtures. Do not require translation of designer Lorem/numeric arrows; report them separately.''',
'''BEFORE/AFTER separately: uppercase262, fallback64 actionable +3 Lorem, dropdown45, event-method34, lookup88. Report remaining misses with full typed examples, and ensure no newly writable technical fields. Re-run independent parser on injected-copy objects; names/methods/resource IDs must be unchanged. Negative control must fail known_renderer_uppercase plus the new positive/negative field fixtures.''')]
for filename,title,size,files,evidence,change,tests,metric in briefs:
    text=f'# {title} (size {size}, defect, writer)\n\n'+common+f'\nFiles to edit: {files}.\n\n## Evidence\n{evidence}\n\n## Change\n{change}\n\n## Tests (must fail on old code)\n{tests}\n'+verify+metric+'\n'+gates
    (R/filename).write_text(text,encoding='utf-8')
print('Five writer briefs generated')
