from pathlib import Path
import json,collections,sys
ROOT=Path(__file__).resolve().parent
sys.stdout.reconfigure(encoding='utf-8',errors='backslashreplace')
inv=json.loads((ROOT/'inventory.json').read_text())
print('Top-level',dict(collections.Counter(Path(f['path']).parts[3] for f in inv)))
print('Translation dumps',[f for f in inv if any(x in f['path'].lower() for x in ['autotranslator','autogeneratedtranslation','bepinex','/languages/','/localization/'])])
print('Data files',[f for f in inv if Path(f['path']).name=='data.unity3d' or (Path(f['path']).suffix=='.assets' and len(Path(f['path']).parts)<8)])
import UnityPy
for game in ['CCTV_WINDOWS_1_3_FULL','CCTV_USSR_WINDOWS_FULL','Sunkissed_windows_full','es/BOXMAN_v0.5.02_x64']:
    data=next((Path(r'D:\juegos\unity')/game).glob('*_Data'))
    candidates=list(data.glob('*.assets'))+list(data.glob('level*'))+list(data.glob('data.unity3d'))
    out=[]
    for p in candidates:
        if p.suffix=='.resS' or not p.is_file():continue
        try:
            env=UnityPy.load(str(p))
            stats=collections.Counter(o.type.name for o in env.objects)
            print(game,p.name,dict(stats),flush=True)
            for o in env.objects:
                if o.type.name=='TextAsset':
                    d=o.read();s=d.m_Script
                    out.append(dict(file=str(p),node=o.assets_file.name,path_id=o.path_id,name=d.m_Name,script=s))
        except Exception as e:print('ERROR',p,str(e),flush=True)
    (ROOT/(game.replace('/','-')+'-textassets.json')).write_text(json.dumps(out,ensure_ascii=True,indent=2),encoding='utf-8')
    for o in out:print('TEXT',o['name'],repr(o['script'][:350]),flush=True)
