from pathlib import Path
import json,collections,subprocess,hashlib
R=Path(__file__).resolve().parent
REPO=Path(r'C:\Projects\Locust')
SRC=str(REPO/'crates/formats/src/unity.rs');SER=str(REPO/'crates/formats/src/unity_serialized.rs')
base_commit=(R/'snapshot-commit.txt').read_text().strip()
def load(n):return json.loads((R/n).read_text())
b=load('binary-results.json');o=load('oot-result.json');inj=load('oot-injection.json');bi=load('binary-injection.json')
miss=load('oot-misses.json')+load('binary-misses.json');fp=load('binary-fps.json')
mc=collections.Counter(x['cls'] for x in miss);fc=collections.Counter(x['cls'] for x in fp)
source_miss={'dialogue_inline_sprite':f'{SRC}:2028','character_display_name':f'{SRC}:146','dialogue_single_character':f'{SRC}:164','dialogue_other':f'{SRC}:167','binary_bypassed_by_scripts':f'{SRC}:2493','typed_uppercase_label':f'{SER}:1424','typed_dropdown_option':f'{SER}:757','typed_numeric_or_symbol':f'{SER}:1106','typed_placeholder':f'{SER}:1151','typed_other_text':f'{SER}:1409','managed_fallback_value':f'{SER}:1409','managed_character_name':f'{SRC}:1559'}
source_fp={'object_name':f'{SER}:740','event_method_name':f'{SER}:1409','resource_or_localization_key':f'{SER}:1409','performance_test_JSON':f'{SRC}:803'}
lines=['# Unity ground-truth audit', '', f'Baseline: `{base_commit}`. All repository code line citations refer to that committed snapshot, preserved verbatim under `C:\\Users\\Mike\\AppData\\Local\\Temp\\locust-research-unity\\workspace\\crates\\formats\\src`. Other sessions changed HEAD and began editing unity.rs before final delivery; this is a baseline audit, not validation of those unbuilt changes (`provenance.json`). Rebase briefs before dispatching into the current working tree.', '', '## Integrity first', '',
       f'- **{o["inject_controls_damaged"]}/{len(inj)} targeted Out of Touch lines lost embedded formatting controls** (write/skip outcome: `oot-inject.log`). Baseline cause: source stripping + prefix/suffix-only reconstruction ({SRC}:166, {SRC}:247, {SRC}:2049).',
       '- **0 untargeted files changed** in the script-copy probe. 112 original script files SHA-256 checked before/after, 0 changes (`oot-original-hashes.json`; game: `D:\\juegos\\unity\\Out of Touch\\OoT_Data\\SCRIPTS~`).',
       f'- **0 unexpected binary changes**: {bi["objects_checked"]:,} CCTV object payloads checked; exactly 3 targeted objects changed, and only the requested slots changed (`binary-injection.json`; original: `{bi["original"]}`). Original bundle SHA-256 before/after: `{bi["original_hash"]}`.',
       '- Hash coverage is a sample of the entire game trees: every source script plus the complete original CCTV bundle used by the inject probes. Original executables, media and other games were never injected.', '', 'Complete inject examples:', '']
for x in inj:lines.append(f'- `{x["file"]}:{x["path"][5:]}` — BEFORE `{json.dumps(x["text"],ensure_ascii=False)}`; AFTER `{json.dumps(x["after"],ensure_ascii=False)}`.')
lines += ['', '## Oracle and rejected candidates', '',
          '- Game-authored Out of Touch `Characters.txt` declarations, dialogue and `button` records in 112 runtime script files. Identity = absolute file + physical line; speaker set comes from the game, not Locust. Citation: `D:\\juegos\\unity\\Out of Touch\\OoT_Data\\SCRIPTS~\\Characters.txt:4`, `Vol1\\Chapter_0.txt:13`, `Vol1\\Vol1_Menus.txt:6` under that same scripts directory.',
          '- Independent parser: UnityPy **1.25.2** + TypeTreeGeneratorAPI **0.0.10**, installed only in scratch `venv/Lib/site-packages` (global Python 3.13 import failed). Custom schemas generated from each game’s shipped `*_Data/Managed/*.dll`; built-in fields/object tables parsed by UnityPy. Citation examples: `D:\\juegos\\unity\\CCTV_WINDOWS_1_3_FULL\\CCTV_Data\\Managed\\Assembly-CSharp.dll`, `Unity.TextMeshPro.dll` in the same folder; BOXMAN `Boxman_Data/Managed/Elringus.Naninovel.Runtime.dll`.',
          '- Binary positives = successfully parsed nonempty `Text.m_Text`, `TextMeshPro[UGUI].m_text`, dropdown option text, tooltip text, confirmation label, ManagedTextProvider defaultValue; BOXMAN named UI ManagedText assets, CharacterNames and `_ITEMS` category/name cells. `binary-truth.json` preserves every object/path/value. These are serialized renderer/runtime localization fields, **not a claim that every prefab/debug/default value was observed on-screen**.',
          '- BOXMAN runtime table coverage: **63/63 ManagedText UI values**, **380/380 item display cells**, **0/6 CharacterNames**. Data: `D:\\juegos\\unity\\es\\BOXMAN_v0.5.02_x64\\Boxman_Data\\resources.assets`, TextAssets `DefaultUI/START/CREDITS/LOAD/GalleryUI/_ITEMS/CharacterNames`; complete IDs/keys/values in `es-BOXMAN_v0.5.02_x64-textassets.json`.',
          '- Type-tree limits: native generator uses 2022.3.32f1 base layout for Unity 6000 games, plus actual game DLL schemas. String fields only are scored; base references from generated schemas are not scored. Full object reads must succeed. Parser failures are **excluded**, not counted as Locust misses: CCTV 157, USSR 4, Sunkissed 292, BOXMAN 146, Out of Touch 0 (`*-trees.json`, errors carry game file and object ID). Naninovel Script SerializeReference objects were among unsupported BOXMAN objects; scenario recall is **unmeasured**.',
          '- `D:\\juegos\\unity` inventory: CCTV_WINDOWS_1_3_FULL, CCTV_USSR_WINDOWS_FULL, Sunkissed_windows_full, Out of Touch; `es/` copies of all four and BOXMAN_v0.5.02_x64. BOXMAN exists only inside `es/`. Root also has five `*.locust.db` sets and unrelated Outlook/Payoneer files (`inventory.json`, 111,536 files).',
          '- Rejected as oracle: Locust databases (self-produced); Spanish original/translated pairs (unknown provenance, potentially Locust-written); TMP line-breaking character tables and PerformanceTestRun JSON (not dialogue/localization). Existing `es/BOXMAN` is used as **current runtime data**, not as an independently authored translation pair.',
          '- No AutoTranslator/BepInEx/dump path was found in the complete inventory (`inventory.json`; original game roots above). No loose `Localization`/`Languages` text tables were found; the useful tables are embedded TextAssets. UnityEngine.LocalizationModule.dll alone is not localization truth.', '', '## Metrics', '',
          'Recall = matched oracle field occurrences / oracle field occurrences. Binary matching requires file/node + object ID + exact source text, with duplicate occurrences consuming distinct rows. Scripts match file + line; source controls are evaluated separately by injection. Empty strings excluded; numeric/symbol labels and shipped placeholder text are retained and broken out below.',
          '', 'Precision (classified) = confirmed visible-field rows / (confirmed visible-field rows + confirmed technical rows). Unclassified rows are excluded from that denominator. Whole-output precision interval = [TP/extracted, (extracted−FP)/extracted]. **Classified precision is not a whole-game precision estimate.** Object names are classified only after independent MonoScript class resolution: renderer/font/tile/scenario/configuration asset IDs. Three unresolved BOXMAN asset names and three Sunkissed MemoryType names remain unclassified (`independent-headers.json`; original game file/object IDs included).', '',
          '| Scope | Truth | Hits | Misses | Recall | Extracted | TP | FP | Unclassified | Classified precision | Whole-output precision interval | Game data |',
          '|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|']
game_data={'cctv':r'D:\juegos\unity\CCTV_WINDOWS_1_3_FULL\CCTV_Data\data.unity3d','ussr':r'D:\juegos\unity\CCTV_USSR_WINDOWS_FULL\CCTV - USSR_Data\data.unity3d','sunkissed':r'D:\juegos\unity\Sunkissed_windows_full\Sunkissed_Data','boxman':r'D:\juegos\unity\es\BOXMAN_v0.5.02_x64\Boxman_Data'}
for x in b:
    if x['game']=='oot-binary':continue
    lines.append(f'| {x["game"]} binary | {x["truth"]} | {x["hits"]} | {x["misses"]} | {100*x["recall"]:.2f}% | {x["extracted"]} | {x["true_positive_rows"]} | {x["false_positive_rows"]} | {x["unclassified_rows"]} | {100*x["precision_classified"]:.2f}% | {100*x["precision_lower_bound"]:.2f}–{100*x["precision_upper_bound"]:.2f}% | `{game_data[x["game"]]}` |')
lines.append(f'| Out of Touch scripts | {o["truth"]} | {o["hits"]} | {o["misses"]} | {100*o["recall"]:.2f}% | {o["extracted"]} | {o["hits"]} | 0 | {o["unclassified"]} | 100.00% | {100*o["precision_lower_bound"]:.2f}–100.00% | `D:\\juegos\\unity\\Out of Touch\\OoT_Data\\SCRIPTS~` |')
ob=next(x for x in b if x['game']=='oot-binary')
lines.append(f'| Out of Touch binary | {ob["truth"]} | {ob["hits"]} | {ob["misses"]} | {100*ob["recall"]:.2f}% | {ob["extracted"]} combined script/binary rows | {ob["true_positive_rows"]} | {ob["false_positive_rows"]} | see merged denominator | not separately scored | — | `D:\\juegos\\unity\\Out of Touch\\OoT_Data` |')
binary=[x for x in b if x['game']!='oot-binary'];truth=o['truth']+sum(x['truth'] for x in b);hits=o['hits']+sum(x['hits'] for x in b);extracted=sum(x['extracted'] for x in b);false=sum(x['false_positive_rows'] for x in b);unknown=extracted-hits-false
lines += ['', f'Combined physical-field recall: **{hits}/{truth} = {100*hits/truth:.2f}%**. Unique extracted-row denominator: **{extracted}** (Out of Touch counted once); TP **{hits}**, FP **{false}**, unclassified **{unknown}**. Classified precision **{100*hits/(hits+false):.2f}%**; whole-output interval **{100*hits/extracted:.2f}–{100*(extracted-false)/extracted:.2f}%**. Source paths: all oracle/game records in `oot-truth.json` and `binary-truth.json`; counts in `oot-result.json`, `binary-results.json`.', '', '## Miss and false-positive classes', '', '| Kind | Class | Count | Responsible source |','|---|---|---:|---|']
for typ,cnts,srcs in [('miss',mc,source_miss),('FP',fc,source_fp)]:
    for cl,n in cnts.most_common():lines.append(f'| {typ} | {cl} | {n} | `{srcs[cl]}` |')
lines += ['', 'Numeric/symbol fields and designer placeholders are renderer fields, but not all need translation. They are not counted as prose bugs. 275 script rows outside the declared speaker set remain unclassified (some aliases and bilingual continuations); no false-positive claim is made for them. Data: `oot-unclassified.json`, each record includes the source game file and physical line.', '', '## Complete examples (three per class where available)', '']
examples={}
for typ,data in [('miss',miss),('FP',fp)]:
    for cl in sorted({x['cls'] for x in data}):
        vals=[x for x in data if x['cls']==cl]
        if cl=='binary_bypassed_by_scripts':vals=[x for x in vals if x['text'] in ('Return','Exit','Settings')]+[x for x in vals if x['text'] not in ('Return','Exit','Settings')]
        elif cl=='performance_test_JSON':vals=sorted(vals,key=lambda x:len(x['text']))
        elif cl=='typed_placeholder':vals=sorted(vals,key=lambda x:len(x['text']))
        chosen=vals[:3];examples[typ+':'+cl]=chosen
        lines += [f'**{typ}: {cl}** ({len(vals)} total; {len(chosen)} shown; all shown if fewer than three)', '']
        for x in chosen:
            loc=f'{x["file"]}:{x["line"]}' if 'line' in x else f'{x["file"]} :: object {x["path_id"]} :: {x["path"]}'
            lines.append(f'- `{loc}` — `{json.dumps(x["text"],ensure_ascii=False)}`')
        lines.append('')
(R/'class-examples.json').write_text(json.dumps(examples,ensure_ascii=True,indent=2),encoding='utf-8')
lines += ['## Ranked defects (five; all Unity-only)', '', '| Rank | Size | Defect | Measured footprint | Exact symbols/lines | Writer brief |', '|---:|---|---|---|---|---|',
          f'| 1 | M | Inject loses embedded VN controls | 3/3 real-copy probes | `UnityPlugin::inject_text_scripts` `{SRC}:247`; `strip_vn_format_codes` :2037; `split_format_codes` :2049 | `writer-01-controls.md` |',
          f'| 2 | M | Leading sprite modifiers hide dialogue | 3468 misses | `extract_vn_dialogue` `{SRC}:2028`; `extract_text_scripts` :162; `inject_text_scripts` :246 | `writer-02-inline-sprites.md` |',
          f'| 3 | S | Scripts suppress all binary extraction | 5340 renderer fields; includes prefab defaults | `UnityPlugin::extract` `{SRC}:2488 / early return :2493 | `writer-03-mixed-discovery.md` |',
          f'| 4 | M | Technical Object.m_Name enters translation queue | {fc["object_name"]} confirmed FP rows | `SerializedFile::read_mono_strings_object` `{SER}:740`; `mono_name_worth_extracting` :1088 | `writer-04-object-names.md` |',
          f'| 5 | L | Untyped MonoBehaviour scanning confuses UI with control fields | {mc["typed_uppercase_label"]} uppercase UI misses; {mc["managed_fallback_value"]} fallback misses (3 Lorem); {mc["typed_dropdown_option"]} option misses; {fc["event_method_name"]} callback FP; {fc["resource_or_localization_key"]} lookup FP | `mono_script_field_worth_extracting` `{SER}:1409 / uppercase gate :1424; `read_mono_strings_object` :757; `is_mono_engine_noise` :1112 | `writer-05-typed-fields.md` |',
          '', 'All five briefs authorize edits only to `crates/formats/src/unity*.rs` (+ tests inside those files), no dependencies/core/RPG Maker edits. **They can run alongside the RPG Maker writer; they overlap each other and must be serialized or assigned to one Unity writer.** Existing injection routing already supports mixed text/binary batches (`'+SRC+':2552`).',
          '', 'Additional measured backlog: 117 script character display names + 6 ManagedText CharacterNames omitted; 24 one-character dialogue bodies omitted. Scope/cause citations are in the class table; these are not extra dispatch briefs.', '', '## Reproducibility and read-only boundary', '',
          f'- One command: `py -3.13 C:\\Users\\Mike\\AppData\\Local\\Temp\\locust-research-unity\\run_all.py` (details in README.md). Baseline committed snapshot: `{base_commit}`; all nine audited Unity files match that commit after newline normalization (`provenance.json`). Current HEAD/status are recorded separately because another session worked in this repo during the audit.',
          '- CLI built offline in scratch; `CARGO_TARGET_DIR` and `LOCUST_DATA_DIR` both under this audit directory. No cargo command ran in the repo. Five regressions **fail on the old code** (`regression-results.json`); these validate defect triggers, not the oracle.',
          '- No real Windows command-runner sandbox-helper error occurred. PowerShell profile startup and Python/pip temporary-directory permission errors were process errors, not helper failures. Later shell calls used no profile; dependency installer kept its temporary files under scratch.',
          '- **Write-boundary exception:** initial CLI runs used standard persistent lock files outside the requested scratch root (`C:\\Projects\\Locust\\crates\\core\\src\\patch\\lock.rs:30`, `C:\\Users\\Mike\\AppData\\Local\\locust-patch-locks-v1`). Initial shell/pip bootstrap also attempted default profile/Temp locations and failed. The final runner redirects locks using a documented scratch-only core shim (`isolate_cli.py`); the audited Unity source is unchanged. The initial runs did not fully meet the write-only-root constraint.',
          '- No repo edits/commits or game edits were made by this researcher. `provenance.json` contains initial/final observed git status, Unity source hashes, and original-data hash checks. Concurrent session changes are external to this audit.']
(R/'last-report.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
print('Report generated; truth',truth,'hits',hits,'FP',false,'unclassified',unknown)
