import os,re,json,sqlite3,zlib,pickle,io,collections
from pathlib import Path
from inventory import files
G=Path(__file__).parent
class SafeUnpickler(pickle.Unpickler):
 def find_class(self,m,n):raise ValueError((m,n))
def norm(s):
 s=re.sub(r'[ \n]+',' ',s)
 def esc(m):
  x=m.group(1)
  if x=='n':return '\n'
  if x in '{[%':return x*2
  if x.startswith('u'):
   try:return chr(int(x[1:],16))
   except:return '\\'+x
  return x
 return re.sub(r'\\(u[0-9a-fA-F]{4}|.)',esc,s)
LIT=re.compile(r'("""[\s\S]*?"""|\x27\x27\x27[\s\S]*?\x27\x27\x27|"(?:\\.|[^"\\])*"|\x27(?:\\.|[^\x27\\])*\x27)')
def statement(s):
 m=LIT.search(s)
 if not m:return None
 lit=m[0];q=3 if lit.startswith(('"""',"'''")) else 1
 return (s[:m.start()].strip(),norm(lit[q:-q]),s[m.end():].strip())
def canon(s):
 p=statement(s)
 return p[:2] if p else None
def refpath(s):return s.replace('\\','/').removeprefix('game/').lower().removesuffix('c') if s.endswith('.rpyc') else s.replace('\\','/').removeprefix('game/').lower()
def source_map(r):
 gd=Path(r['game']); src={};origin={};compiled=[]
 for a in sorted(gd.glob('*.rpa')):
  with a.open('rb') as f:
   hd=f.readline().split()
   if len(hd)<3:continue
   off=int(hd[1],16);key=int(hd[2],16);f.seek(off)
   try:idx=SafeUnpickler(io.BytesIO(zlib.decompress(f.read()))).load()
   except Exception as e:print('index error',a,e);continue
   for name,segments in idx.items():
    if isinstance(name,bytes):name=name.decode('utf8')
    if not name.endswith(('.rpy','.rpyc')) or name.startswith('tl/'):continue
    rel=refpath(name)
    if name.endswith('.rpyc'):compiled.append(rel);continue
    data=b''
    for seg in segments:
     offset,length=seg[:2];prefix=seg[2] if len(seg)>2 else b''
     if isinstance(prefix,str):prefix=prefix.encode()
     f.seek(offset^key);data+=prefix+f.read(length^key)
    src[rel]=data.decode('utf-8-sig',errors='replace').splitlines();origin[rel]=str(a)+'#'+name
    out=G/'sources'/r['name']/name
    if '..' not in Path(name).parts:
     out.parent.mkdir(parents=True,exist_ok=True);out.write_bytes(data)
 for p in files(gd,'.rpy'):
  if 'tl' in p.relative_to(gd).parts:continue
  rel=refpath(str(p.relative_to(gd)));src[rel]=p.read_text('utf-8-sig',errors='replace').splitlines();origin[rel]=str(p)
 return src,origin,compiled
def parse_tl(r):
 gt={};old=[];headers=0;unparsed=[];raw=0
 for lang in r['languages']:
  for f in files(Path(r['game'])/'tl'/lang['lang'],'.rpy'):
   ls=f.read_text('utf-8-sig',errors='replace').splitlines()
   if '\n'.join(ls).startswith('# Auto-generated by Locust'):continue
   ref=None;block=None;have=False
   for i,line in enumerate(ls,1):
    t=line.strip();m=re.match(r'#\s*([^#].+\.rpyc?):(\d+)$',t)
    if m:ref=(refpath(m[1]),int(m[2]));continue
    m=re.match(r'translate \S+ (\S+):$',t)
    if m:
     if block and not have:unparsed.append(block)
     block=None if m[1]=='strings' else {'id':m[1],'tl':str(f),'tl_line':i};have=False
     if block:headers+=1
     continue
    if block and t.startswith('# '):
     stmt=t[2:].strip();p=statement(stmt)
     if not p:continue
     # Generated block comments carrying say statements; reject voice/python helpers.
     if p[0].split(' ')[0] in ['play','with','pause','$','pass','call','jump']:continue
     if not ref:continue
     have=True;raw+=1
     key=(ref[0],ref[1],p[0],p[1]);gt.setdefault(key,dict(block,ref=list(ref),statement=stmt,text=p[1],who=p[0],comment_line=i));block=None
    if t.startswith('old '):
     p=statement(t[4:])
     if p:old.append({'ref':ref,'text':p[1],'tl':str(f),'tl_line':i})
   if block and not have:unparsed.append(block)
 return list(gt.values()),old,headers,raw,unparsed
def trace(lines):
 result={};menu=False;py=False;pi=0;depth=0
 for n,line in enumerate(lines,1):
  t=line.strip();indent=len(line)-len(line.lstrip())
  if depth==0 and t.startswith('define '):
   depth=max(0,sum(t.count(x) for x in '{[(')-sum(t.count(x) for x in '}])'))
  elif depth>0:
   depth=max(0,depth+sum(t.count(x) for x in '{[(')-sum(t.count(x) for x in '}])'));result[n]='define bracket suppression';continue
  if t.startswith(('python:','init python:')) or (t.startswith('init -') and 'python:' in t):py=True;pi=indent
  if py and t and indent<=pi and not t.startswith(('python:','init ','#')):py=False
  if t.startswith('#'):continue
  if t=='menu:' or (t.startswith('menu ') and t.endswith(':')):menu=True;continue
  if menu:
   p=statement(t)
   if p and not p[0] and (not p[2] or p[2].startswith(':')):result[n]='menu choice/prompt';continue
   if t and not t.startswith(('"','jump','pass','#')) and not (line.startswith('        ') or line.startswith('\t\t')):menu=False
  result[n]='python block' if py else 'menu state suppression' if menu else ''
 return result
if __name__=='__main__':
 summaries=[];misses=[];extras=[];unparsed_all=[]
 for r in json.loads((G/'selected.json').read_text()):
  db=G/(r['name']+'.locust.db')
  if not db.exists():continue
  conn=sqlite3.connect('file:'+str(db)+'?mode=ro',uri=True);conn.row_factory=sqlite3.Row
  entries=[dict(e) for e in conn.execute('select id,source,context,tags,metadata,file_path from strings')]
  dialogue=[e for e in entries if set(json.loads(e['tags']))&{'dialogue','menu','scroll_text'}]
  gt,old,headers,raw,unparsed=parse_tl(r);unparsed_all.extend(unparsed)
  src,origin,compiled=source_map(r);traces={f:trace(ls) for f,ls in src.items()}; src_canon={f:{canon(x) for x in ls} for f,ls in src.items()}
  byref=collections.defaultdict(list);bytext=collections.defaultdict(list)
  for e in dialogue:
   txt=norm(e['source']) if 'rpyc' not in json.loads(e['tags']) else e['source'];e['text']=txt;bytext[txt].append(e)
   loc=e['id'].rsplit('#',1)
   if len(loc)==2 and loc[1].isdigit():
    fp=Path(e['file_path']);file=refpath(str(fp.relative_to(Path(r['game'])))) if fp.suffix=='.rpy' else None
    if file is None:
     stem=loc[0].rsplit('#',1)[-1].lower();opts=[f for f in src if Path(f).name==stem]
     if len(opts)==1:file=opts[0]
    e['ref']=[file,int(loc[1])]
    if file:byref[(file,int(loc[1]))].append(e)
  hits=0;exact=0;corrected=0;stale=0;live=0
  for b in gt:
   file,n=b['ref'];ls=src.get(file,[]);current=ls[n-1].strip() if 0<n<=len(ls) else ''
   b.update(game=r['name'],current=current,origin=origin.get(file,''),trace=traces.get(file,{}).get(n,''))
   p=statement(current)
   b['live_at_ref']=bool(p and p[1]==b['text'])
   if b['live_at_ref']:live+=1
   candidates=byref.get((file,n),[])
   if any(e['text']==b['text'] for e in candidates):hits+=1;exact+=1;continue
   # Canonical text fallback restricted to same speaker when context is available; compiled rows have no context.
   who=b['who'].split(' ')[0] if b['who'] else None
   matches=[] if b['live_at_ref'] else [e for e in bytext.get(b['text'],[]) if (e['context']==who or 'rpyc' in json.loads(e['tags']) or e.get('ref',[None])[0]==file)]
   if matches:hits+=1;continue
   if current.startswith('#') and canon(current.lstrip('#').strip())==canon(b['statement']):
    cls='stale tl: source statement now commented out'
   elif not b['live_at_ref'] and file in src:
    if canon(b['statement']) in src_canon[file]:cls='reference drift, statement exists elsewhere'
    else:cls='stale tl: statement absent/changed';stale+=1
   elif file not in src:cls='compiled/archive source unavailable'
   elif b['trace'] in ['menu state suppression','python block','define bracket suppression']:cls=b['trace']
   elif current.startswith("'") or (p and "'" in current and '"' not in current):cls='single-quoted say'
   elif p and ('.' in p[0] or '-' in p[0] or '@' in p[0]):cls='speaker expression/attributes'
   elif current.startswith('_'):cls='underscore speaker rejected'
   elif current.startswith('extend '):cls='extend'
   elif p and not p[1]:cls='empty text'
   elif '"""' in current or "'''" in current:cls='multiline/triple-quoted say'
   elif candidates:cls='wrong/truncated extracted literal'
   else:cls='other parser rejection'
   b['class']=cls;misses.append(b)
  gtext={b['text'] for b in gt};otext={b['text'] for b in old};alltext=gtext|otext
  allstmt=set()
  fpcounts=collections.Counter()
  for e in dialogue:
   if e['text'] in alltext:continue
   e.update(game=r['name']);ref=e.get('ref');current='';state=''
   if ref and ref[0] in src:
    ls=src[ref[0]];current=ls[ref[1]-1].strip() if 0<ref[1]<=len(ls) else '';state=traces[ref[0]].get(ref[1],'')
   e.update(current=current,trace=state)
   if 'rpyc' in json.loads(e['tags']):cls='compiled unmatched: requires AST verification'
   elif not current:cls='archive basename locator: unavailable'
   elif re.match(r'^(?:font|color|outlines|x\w+|y\w+|align|anchor|box_\w+|mouse|value|button|timer|vbox|hbox|frame|window)\b',current):cls='screen/style property code literal'
   elif '"""' in current or "'''" in current:cls='triple-quote spurious/truncated literal'
   elif state=='menu choice/prompt' or 'menu' in json.loads(e['tags']):cls='menu not in tl strings (coverage unknown)' if current.endswith(':') else 'quoted code/data or unlisted narration'
   elif current.startswith('translate '):cls='translate header code literal'
   elif statement(current):cls='quoted code/data or unlisted narration' if current.endswith((',',']',')','}')) and current.startswith(('"',"'")) else 'current say not in tl (coverage unknown)'
   else:cls='other code literal'
   e['class']=cls;fpcounts[cls]+=1;extras.append(e)
  count=len(dialogue);unmatched=sum(fpcounts.values())
  summaries.append({'name':r['name'],'tl_headers_all_languages':headers,'raw_statements_all_languages':raw,'unique_tl_statements':len(gt),'matched':hits,'exact_ref_and_text':exact,'recall':round(hits/len(gt)*100,4),'dialogue_rows':count,'not_in_tl':unmatched,'precision_ish':round((count-unmatched)/count*100,4),'live_at_ref':live,'source_files':len(src),'compiled_files':len(compiled),'extra_classes':dict(fpcounts),'old_strings':len(otext)})
  print(summaries[-1],flush=True)
 for name,data in [('summary',summaries),('unparsed',unparsed_all)]: (G/(name+'.json')).write_text(json.dumps(data,ensure_ascii=False,indent=2),encoding='utf8')
 for name,data in [('misses',misses),('extras',extras)]:
  with (G/(name+'.jsonl')).open('w',encoding='utf8') as f:
   for b in data:f.write(json.dumps(b,ensure_ascii=False)+'\n')
 print('MISSES',collections.Counter(b['class'] for b in misses));print('EXTRAS',collections.Counter(b['class'] for b in extras));print('UNPARSED',len(unparsed_all))
 
 
 
