import os,json,re
from pathlib import Path
G=Path(__file__).parent
SKIP={'.locust','.locust-injections','.locust_backups','renpy','lib','.git','cache'}
def files(root,suffix):
 for d,ds,fs in os.walk(root):
  ds[:]=[x for x in ds if x not in SKIP and not x.startswith('backup')]
  for f in fs:
   if f.endswith(suffix):yield Path(d)/f
if __name__ == '__main__':
 rows=[]
 for top in sorted(Path(r'D:\juegos\renpy').iterdir()):
  if not top.is_dir():continue
  gd=top/'game'
  if not gd.is_dir():
   candidates=[p/'game' for p in top.iterdir() if p.is_dir() and (p/'game').is_dir()]
   if not candidates:continue
   gd=candidates[0]
  if not (gd/'tl').is_dir():continue
  langs=[]
  for lang in sorted((gd/'tl').iterdir()):
   if not lang.is_dir():continue
   fs=list(files(lang,'.rpy')); n=0; real=0
   for f in fs:
    text=f.read_text('utf-8-sig',errors='replace')
    if text.startswith('# Auto-generated by Locust'):continue
    real+=1;n+=len(re.findall(r'^translate \S+ \S+_[0-9a-f]{8}(?:_\d+)?:',text,re.M))
   if n:langs.append({'lang':lang.name,'blocks':n,'files':real})
  if not langs:continue
  loose=[p for p in files(gd,'.rpy') if 'tl' not in p.relative_to(gd).parts]
  rpyc=[p for p in files(gd,'.rpyc') if 'tl' not in p.relative_to(gd).parts]
  rows.append({'name':top.name,'root':str(gd.parent),'game':str(gd),'loose':len(loose),'rpyc':len(rpyc),'rpa':len(list(gd.glob('*.rpa'))),'languages':langs})
  print(rows[-1],flush=True)
 G.joinpath('inventory.json').write_text(json.dumps(rows,indent=2),encoding='utf-8')
 
